### ISSUE TITLE
Update Theme 2021 Hacktoberfest

### ISSUE THREAD

**Issue by PyladiesTNR** [PyladiesTNR/Hackotberfest-PyladiesTNR-2021#15]
- [ ] Change README Banner
- [ ] Fix typos
- [ ] Update contribution steps

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Can you elaborate more on the 3rd point?
Thanks

**Comment by techyAdi1** [comment]
Hi can I work on this issue?

**Comment by PyladiesTNR** [comment]
@himanshu007-creato
1. The banner should be changed to this image
![hack2021-light](https://user-images.githubusercontent.com/57705801/135631172-2cc14ad0-c97c-4a98-8d0d-42d26d7b2eb6.png)
2. The contribution steps on the readme might be missing - or we might forgot something | you may update them or change them to be more user-friendly
